### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by martinaucher** [GreenWaves-Technologies/MobilenetV1_Pytorch#2]
Hi,

I encounter an issue at running time without changing anything after cloning the repo.

`Construct OK`
`The final class is 870`
`Checksum wrong! Current value is 870`

But the expected class is 144.

I just run the command `make all run`

SDK Version : 3.7.1

Thanks

**Comment by Pafrak** [comment]
We fixed it with latest release. Can you try it again?
